### PR TITLE
Feature/needle 2023

### PR DESCRIPTION
**Pull request by mariusconjeaud**
Phase 1 of redesign with Needle.

- Add Needle as dependency and default styling
- Implemented Tailwind
- Replaced some MUI components with Needle components

### CODE REVIEW

**Comment by mariusconjeaud** [comment]
Draft PR to interact on minor fixes with Needle team.

Cypress tests haven't been run - and fixed - yet

**Comment by BennuFire** [comment]
I just added a commit that migrates every mui4 element that was still around into mui5. 
The mui5 elements around got a theme provider injection so they are Needle-ish.
A few things to adjust on the rule based styling modal, but overall looks good.

**Comment by mariusconjeaud** [comment]
Hmmmm... It looks like it added a gutter to the sides of the report area

image

**Comment by mariusconjeaud** [comment]
Fixed previous comment by overriding the default CSS breakpoints of MUI 5

**Comment by mariusconjeaud** [comment]
Fixed the rule-based styling modal ; updated TextInput for settings to Needle components ; fixed the node properties dropdown in the graph chart

=> this is now ready according to me @nielsdejong @BennuFire

**Review by nielsdejong — APPROVED** [review]

**Review by nielsdejong — APPROVED** [review]

**Comment by konsalex** [comment]
Let's go guys! 🚀

**Pull request merged**
