### PR TITLE
Adding Needle integration

### PR DESCRIPTION
**Pull request by mariusconjeaud**
Replaces as many Mui components as possible by Needle components

### CODE REVIEW

**Comment by mariusconjeaud** [comment]
Replaced components :

- Icon
- Button & IconButton
- Dialog
- Dropdown (when no autocomplete)
- Slider
- Spinner
- Typography (except in non Needle components like Table, Charts, ...)

Things to fix :
- Load dashboard from file not triggering
- Full screen dialog higher than page

**Comment by mariusconjeaud** [comment]
Untested parts :
- LoadSharedDashboard dialog
- Share from Neo4j
- UpgradeOldDashboard
- SSO Login

**Comment by mariusconjeaud** [comment]
Next things to add :

- [ ] Cards
- [ ] Tabs ?
- [ ] Test out tables
- [ ] Autocomplete for dropdowns (dynamic options)
- [ ] Use TextInput components for no-border inputs (Dashboard title, Report title, Tab title)

**Comment by Sebastiannilsson1** [comment]
Can you also add @konsalex for review so he can help with the proper configuration?

**Comment by BennuFire** [comment]
Should we close this one @mariusconjeaud ?

**Pull request closed without merging**
