### PR TITLE
[Feature #884] Helm chart for Kubernetes deployments

### PR DESCRIPTION
**Pull request by venkatalolla**
## PR Description
This is a new feature request to create a Helm chart to support the Kubernetes based deployments in a package pattern. This Helm chart should enable the NeoDash deployment in either editor or reader mode for easy versioning, packaging and installing these dashboards at an enterprise level.

The solution includes a Helm chart with the following Kubernetes resources templates to support the editor or reader mode for ease of deployment,

- Deployment
- Service
- Service Account
- Ingress (Optional)
- Values file (Default configurations)
- Along with the Helm chart, add the appropriate documentation about the usage and default values.

As an alternative solution I also included the required Kubernetes YAML files to deploy the NeoDash with Kubectl commands.
#884

### CODE REVIEW

**Comment by alfredorubin96** [comment]
Hi @venkatalolla, thank you for your contribution! Could you please check the warning that are popping up in this page and check whether they are critical or not? 

Thanks again for helping the project!

**Comment by venkatalolla** [comment]
Hey @alfredorubin96 if you're talking about the sonarcloud warning, I already fixed them in my last commit, and they're gone now. Just so you know, they weren't critical anyway.

**Comment by alfredorubin96** [comment]
Looked at the code and sounds good to me, could you please provide me an easy way to test it? I'm not an expert in developing helm charts, but there is a way in which we can test the deployment inside our pipelines?

**Comment by venkatalolla** [comment]
Hello @alfredorubin96, Thank you for the response. For testing the Helm chart deployment, I have put together a GitHub workflow in my own repository, [https://github.com/venkatalolla/neodash-kind-helm-workflow](https://github.com/venkatalolla/neodash-kind-helm-workflow), that deploys the Helm chart to a local KinD Kubernetes cluster and validates the 200 response for the NeoDash URL using CURL.

For your information, I have tested the above-shared workflow [here](https://github.com/venkatalolla/neodash-kind-helm-workflow/actions/runs/9584672808/job/26428827124) using the same code from this PR as an example.

Let me know if you want me to provide more details on the GitHub workflow or the deployment.

**Comment by venkatalolla** [comment]
@alfredorubin96, please let me know if you need more information on my last comment.

**Comment by msenechal** [comment]
Moved to PR #971 for small changes/typo

**Comment by nielsdejong** [comment]
Closing as this is moved to #971

**Pull request closed without merging**
