### PR TITLE
Hotfix on CSV Extract from NeoDash

### PR DESCRIPTION
**Pull request by JonanOribe**
Partial solution to "CSV Extract from NeoDash adds quotes and leading white space" #363.

The white spacing is solved, but I'm not able to reproduce the quotes problem (I'm trying with different versions of Excel and LibreOffice), so I upload the hotfix but I will continue looking about how to induce a failure with the quotes.

No more leading white spaces on headers or data.

Excel
image

LibreOffice
image

### CODE REVIEW

**Review by nielsdejong — APPROVED** [review]

**Review by NanisTe — COMMENTED** [review]
Just an idea. Independent of the data. But numbers on MacOS usually introduces quotes at least as soon as there are comma in text fields and at the same time comma is used as a separator. So there seems to be some algorithm checking on this in Numbers.

Which leads actually to one of my issues, that it would be nice to choose the sperator to be used when exporting a csv in NeoDash.

**Comment by nielsdejong** [comment]
Hi @NanisTe , I agree, it would be very nice to have an advanced setting in the table report to choose the seperator. 
Perhaps people can choose from `,`, `;`, or `\t` as a starting point.

**Comment by NanisTe** [comment]
@nielsdejong yes those separators would be great to have. Currently we can not use our extracts from NeoDash because they are regularly having issues with the comma.

**Comment by nielsdejong** [comment]
Hi @JonanOribe and @NanisTe ,

Thanks for your ideas and work here. @JonanOribe  I've extended your branch to include the addition of seperators as well so we can get both in simultaniuously.

**Pull request merged**
